# Generated by Django 3.2.8 on 2021-10-18 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_1",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "field_2",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "field_3",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "field_4",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "field_5",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "field_6",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "field_7",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "field_8",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "field_9",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O"), ("", "Blank")],
                        default="",
                        max_length=1,
                    ),
                ),
                ("move", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "player_O",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_o",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_X",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_x",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
